# Generated by Django 5.2.3 on 2025-07-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
            migrations.AddField(
            model_name='purpose',
            name='purpose',
            field=models.CharField(max_length=20, choices=[('QC', 'QC'),
        ('SNAGGING', 'Snagging'),], default='QC'),),
    ]
