# Generated by Django 5.2.3 on 2025-07-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_purpose_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purpose',
            old_name='purpose',
            new_name='name',
        ),
    ]
