# Generated by Django 5.2.3 on 2025-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_purpose_purpose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrule',
            name='Zone_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(default='QC', max_length=20),
        ),
    ]
