# Generated by Django 5.2.3 on 2025-07-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_transferrule_zone_level_alter_purpose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('assigned_by', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('delete', models.BooleanField(default=False)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_purposes', to='projects.allpurpose')),
            ],
        ),
    ]
